services:
  - type: web
    name: ubid-mesh
    env: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
